name: Mirror to TELCOM Org

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Debug PAT value (Temporary - Remove in production)
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          echo "Length of PAT secret: ${#PAT}"
          # Or for basic visibility (be careful in public repos)
          echo "PAT starts with: ${PAT:0:4}********"

      - name: Push code to second org repo
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add mirror https://x-access-token:${PAT}@github.com/TLCFZC/mirror_spos.git
          git push -u mirror main
