name: Mirror to TELCOM Org

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clean old remote if any
        run: |
          echo "Cleaning up remote if it exists..."
          git remote remove mirror || true

      - name: Add remote with PAT
        run: |
          echo "Adding mirror remote with PAT"
          git remote add mirror https://x-access-token:${{ secrets.PAT }}@github.com/TLCFZC/mirror_spos.git

      - name: Test access to mirror repo
        run: |
          echo "Testing access with git ls-remote..."
          git ls-remote mirror || (echo "Access failed!" && exit 1)

      - name: Push to mirror
        run: |
          echo "Pushing to mirror repo..."
          git push mirror main --force
