name: Mirror to TELCOM Org

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0       # Ensure full history is fetched
          ref: main            # Explicitly checkout the main branch

      - name: Debug token access
        run: |
          curl -i -H "Authorization: token ${{ secrets.PAT }}" https://api.github.com/repos/TLCFZC/mirror_spos     

      - name: Show remotes
        run: |
          git remote -v
          git ls-remote https://x-access-token:${{ secrets.PAT }}@github.com/TLCFZC/mirror_spos.git || echo "Access failed"


      - name: Set up Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"


      - name: Confirm PAT is available
        run: echo "Length of PAT: ${#{{ secrets.PAT }}}"

      - name: Push code to TELCOM org repo
        run: |
          echo "Remote before cleanup:"
          git remote -v

          # Remove remote if already exists
          git remote remove mirror || true

          echo "Adding remote with PAT..."
          git remote add mirror https://x-access-token:${{ secrets.PAT }}@github.com/TLCFZC/mirror_spos.git

          echo "Remote after adding:"
          git remote -v

          echo "Trying git ls-remote to test access..."
          git ls-remote mirror || echo "Still failed"

          echo "Pushing to mirror..."
          git push mirror main --force

