name: Mirror to TELCOM Org

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0       # Ensure full history is fetched
          ref: main            # Explicitly checkout the main branch

      - name: Set up Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push code to TELCOM org repo
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git remote add mirror https://x-access-token:${PAT}@github.com/TLCFZC/mirror_spos.git
          git push mirror main --force
